### ISSUE TITLE
Block

### ISSUE THREAD

**Issue by LordOfBans** [Sibes991/-gitflow-branch-1-#2]
I know you don't like being contradicted than blocking everyone who doesn't think like you. You don't listen to any arguments other than yours for not being right. You can report and block me, I just wanted you to read this and realize how sad it is. On every page I find you you have the same argument. Prove it im wrong. Don't you see how implausible that is? You look like an adult now. Don't act like a child Matt

**Comment by Sibes991** [comment]
I'm not the one who doesn't listen. You have no mind to look at the fact or even try thing yourself. It's pathertic how you then jump on anyone who disagrees
